import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";
import { getCurrentUserId } from "@/lib/auth";

const supabase = createClient(
    process.env.SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
);

export async function POST() {
    // 1. Resolve user (temporary)
    const userId = await getCurrentUserId();

    // 2. Fetch Notion token
    const { data, error } = await supabase
        .from("user_integrations")
        .select("access_token")
        .eq("user_id", userId)
        .eq("provider", "notion")
        .single();

    if (error || !data) {
        return NextResponse.json(
            { error: "Notion not connected" },
            { status: 401 }
        );
    }

    const notionToken = data.access_token;

    // 3. Create roadmap page in Notion
    const notionRes = await fetch("https://api.notion.com/v1/pages", {
        method: "POST",
        headers: {
            "Authorization": `Bearer ${notionToken}`,
            "Content-Type": "application/json",
            "Notion-Version": "2022-06-28"
        },
        body: JSON.stringify({
            parent: { type: "workspace", workspace: true },
            properties: {
                title: {
                    title: [
                        {
                            text: {
                                content: "AI Career Roadmap (Generated by MindMesh)"
                            }
                        }
                    ]
                }
            },
            children: [
                {
                    object: "block",
                    type: "heading_2",
                    heading_2: {
                        rich_text: [{ text: { content: "Phase 1: Foundations" } }]
                    }
                },
                {
                    object: "block",
                    type: "bulleted_list_item",
                    bulleted_list_item: {
                        rich_text: [{ text: { content: "Learn Python & Data Structures" } }]
                    }
                },
                {
                    object: "block",
                    type: "bulleted_list_item",
                    bulleted_list_item: {
                        rich_text: [{ text: { content: "Understand ML Basics" } }]
                    }
                },
                {
                    object: "block",
                    type: "heading_2",
                    heading_2: {
                        rich_text: [{ text: { content: "Phase 2: Applied Skills" } }]
                    }
                },
                {
                    object: "block",
                    type: "bulleted_list_item",
                    bulleted_list_item: {
                        rich_text: [{ text: { content: "Build 2 ML Projects" } }]
                    }
                },
                {
                    object: "block",
                    type: "bulleted_list_item",
                    bulleted_list_item: {
                        rich_text: [{ text: { content: "Participate in Hackathons" } }]
                    }
                }
            ]
        })
    });

    const notionData = await notionRes.json();

    if (!notionRes.ok) {
        return NextResponse.json(
            { error: "Failed to create roadmap", details: notionData },
            { status: 500 }
        );
    }

    return NextResponse.json({
        success: true,
        notionPageId: notionData.id
    });
}
